version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: versionone
    container_name: versionone-app
    restart: unless-stopped
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - versionone
  db:
    image: mysql:8.0
    container_name: versionone-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ../versionone_mysql_data:/var/lib/mysql
    networks:
      - versionone
  nginx:
    image: nginx
    container_name: versionone-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - versionone
    depends_on:
      - app
networks:
  versionone:
    driver: bridge
volumes:
  mysql_data: